Выделение исполняемого файла #1
lyawaf/antivirus pull request #10
Opened 2019-05-24 12:01 UTC by Katrinehey

2019-05-24 15:09 UTC, maurges requested changes

2019-05-24 15:09 UTC, d86leader commented on select_executable.py
> +                               dd='[(,\b{0,1}](elf)|(mach-o)|(pe)[\b,)]')
Внутри `[]` фигурные скобки не работают, поэтому тут заматчится, например, `0elf`.
На `PE` слишком слабое выражение: матчится, например, `philippe,`

2019-05-24 15:09 UTC, d86leader commented on select_executable.py
> +# save directory /_filename.extracted with all elf, mach-o, pe extracted files to /dirpath
Перефразируй, пожалуйста, мне не понятно до запятой.

2019-05-24 17:55 UTC, Katrinehey commented on select_executable.py
> +# save directory /_filename.extracted with all elf, mach-o, pe extracted files to /dirpath
Исправила. Теперь, возможно, звучит получше.

2019-05-24 17:58 UTC, Katrinehey commented on select_executable.py
> +                               dd='[(,\b{0,1}](elf)|(mach-o)|(pe)[\b,)]')
Разделила ключевые слова + 'pe' заменила 'microsoft executable'

2019-05-25 11:48 UTC, vveiln commented on select_executable.py
> +def select_executable(filepath, dirpath):
мб лучше extract? привычнее + каноничнее

2019-05-25 11:48 UTC, vveiln commented on select_executable.py
> +import binwalk
shebang line

2019-05-25 12:03 UTC, vveiln commented on select_executable.py
> +        print("Critical failure:", e)
Кстати да, в чем смысл обработки ошибки, когда она бы и так вывелась, но при этом прервалась бы работа?

2019-05-25 15:18 UTC, d86leader commented on select_executable.py
> +import binwalk
Какой шебанг, это же модуль незапускаемый (по идее)

2019-05-25 15:22 UTC, d86leader commented on select_executable.py
> +        print("Critical failure:", e)
Обработка ошибки нужна, чтоб у нас UI не упал, и ошибка в него корректно ушла.

2019-05-25 15:28 UTC, vveiln commented on select_executable.py
> +        print("Critical failure:", e)
Кажется не очень здоровым иметь _неявную_ зависимость кода от ui

2019-05-25 15:37 UTC, d86leader commented on select_executable.py
> +        print("Critical failure:", e)
Ага, поэтому зависимость очень явная (будет). Явно указывать прогресс и явно говорить пользователю об ошибках.

2019-05-25 16:16 UTC, vveiln commented on select_executable.py
> +        print("Critical failure:", e)
В этом коде будет?

2019-05-25 16:20 UTC, d86leader commented on select_executable.py
> +        print("Critical failure:", e)
Ну да, это же код, который что-то делает. Если код что-то делает, то ему стоит об этом сказать пользователю, чтобы тот не думал, что всё зависло.
А вот как она будет реализована - я вижу два варианта.

2019-05-26 05:05 UTC, Katrinehey commented on select_executable.py
> +def select_executable(filepath, dirpath):
+

2019-05-26 05:07 UTC, Katrinehey commented on select_executable.py
> +import binwalk
Можно поподробней, в чем тут проблема?

2019-05-26 07:11 UTC, vveiln commented on select_executable.py
> +import binwalk
Можно почитать подробнее в соседнем пулл реквесте, но если совсем коротко: можно и забить на это

2019-05-26 07:13 UTC, vveiln commented on select_executable.py
> +        print("Critical failure:", e)
Я про то, что я буду смотреть на эту конкретную функцию и видеть там не бессмысленный отлов эксепшенов и принт ошибки, а хотя бы причину, по которой это происходит

2019-05-26 07:29 UTC, Katrinehey commented
Кстати, хотела сказать, что тут у меня нет рекурсивной распаковки архивов и их проверки (но можно попробовать как-нибудь сделать). Поэтому скорее всего с dmg файлами (возможно, с какими-то другими) работать корректно не будет, так как там на верхнем уровне всегда куча архивов, а основные исполняемые файлы где-то в них. Но я решила так сильно не заморачиваться, это проблема? Следует ли думать в эту сторону?

2019-05-27 05:45 UTC, vveiln commented
Господи, какие тут коменты неудобные. Не, забей на сложные файлы. Типа есть два пути: либо все делать суперуниверсальным и тратить на какие-то рутинные штуки кучу времени, либо ограничить функционал, скажем, вдвое, но сократить время бессмысленной работы в четыре раза. Я вот за второй подход, поэтому не вижу смысла предусматривать вообще все кейсы этого мира, главное потом обозначить область действия и все

2019-06-03 06:37 UTC, Katrinehey commented on select_executable.py
> +        print("Critical failure:", e)
`+`, убрала все

2019-06-03 06:59 UTC, Katrinehey commented on select_executable.py
> +import binwalk
`+`, добавила

2019-06-03 09:37 UTC, maurges requested changes

2019-06-03 09:37 UTC, d86leader commented on extract.py
> +def extract(filepath, dirpath):
Не хватает информации о кидаемых функцией исключениях. Мы хотели её добавить взамен убранного `try ... except`

2019-06-03 15:15 UTC, Katrinehey commented on extract.py
> +def extract(filepath, dirpath):
`+`

2019-06-03 16:04 UTC, maurges approved these changes

2019-06-03 16:05 UTC, d86leader commented
Добро.

2019-06-04 07:53 UTC, merged