[+] ./main invoker
lyawaf/antivirus pull request #11
Opened 2019-05-24 14:26 UTC by kiselyovanat

2019-05-24 15:09 UTC, maurges requested changes

2019-05-24 15:09 UTC, maurges commented on CCPTool/invoke_layer.py
> +    return(output,errors)
Нет парсинга результатов же. Нужно ещё где-то в этом враппере делать вывод по поводу вирус ли это (как я понял из ишью)

2019-05-25 00:14 UTC, kiselyovanat commented on CCPTool/invoke_layer.py
> +    return(output,errors)
Когда с Юлей обсуждали, что нужно сделать, речь шла о сохранении результата и все. Так что надо до конца определиться, что все-таки сделать нужно в конечном итоге: нужно парсить мне, или это уже задача другой функции.

2019-05-25 11:59 UTC, vveiln reviewed
Напиши класс эксепшенов, чтобы их кидать

1. Если нет мэйна
2. Если мэйн валится

https://github.com/vveiln/python-internship/blob/develop/src/transport_exception.py
можно использовать в качестве примера

2019-05-25 11:59 UTC, vveiln commented on CCPTool/invoke_layer.py
> +import subprocess
shebang line

2019-05-25 11:59 UTC, vveiln commented on CCPTool/invoke_layer.py
> +    command = ['./main', filename]
1. а что, если скрипт вызывается из другой директории?
2. хорошо бы, наверное, сделать проверку на существование исполняемого файла и, если его нет, кидать эксепшн

2019-05-25 11:59 UTC, vveiln commented on CCPTool/invoke_layer.py
> +    return(output,errors)
1. пробел после return
это tuple, а не аргументы return'а все же

2.  пробел после запятой

2019-05-25 11:59 UTC, vveiln commented on CCPTool/invoke_layer.py
> +    return(output,errors)
Вообще, конечно, хорошо бы парсить, да. На минималках можно захардкодить ответы и заменить на yes/no, только более descriptive

На ошибках эксепшн кидать

2019-05-25 15:19 UTC, d86leader commented on CCPTool/invoke_layer.py
> +import subprocess
Какой шебанг, это же модуль незапускаемый

2019-05-25 15:26 UTC, vveiln commented on CCPTool/invoke_layer.py
> +import subprocess
Чтобы больше никогда не заботиться о том, запускаемый он или нет, что бы ни менялось в механизме

2019-05-25 15:35 UTC, d86leader commented on CCPTool/invoke_layer.py
> +import subprocess
М-кей, пойду напишу во все свои файлы шебанги тоже.

2019-05-25 16:15 UTC, vveiln commented on CCPTool/invoke_layer.py
> +import subprocess
Ну, типа у меня пока нет четкого представления о том, как оно будет работать в будущем, поэтому я в таких случаях ставлю, а потом убираю, а не наоборот. Пока не критично, конечно

2019-06-16 15:33 UTC, maurges requested changes

2019-06-16 15:33 UTC, d86leader commented on invoke_layer.py
> +        return
`return` избыточен. `raise` и так заставит уйти из функции.

2019-06-16 15:33 UTC, d86leader commented on invoke_layer.py
> +        NoMainException(exc)
Исключение создаётся и тут же удаляется? Наверное ты хотела сделать `raise NoMainException`. И тогда следующие две строки тоже станут ненужными.

2019-06-16 16:30 UTC, kiselyovanat commented on CCPTool/invoke_layer.py
> +    return(output,errors)
сделано

2019-06-16 16:42 UTC, kiselyovanat commented on invoke_layer.py
> +        NoMainException(exc)
![image](https://user-images.githubusercontent.com/28254916/59566901-58bd4480-9090-11e9-9d1e-26785009f71c.png)
когда писала, с raise отрабатывал странно.. вот пример

2019-06-16 16:46 UTC, kiselyovanat commented on invoke_layer.py
> +        NoMainException(exc)
![image](https://user-images.githubusercontent.com/28254916/59566936-e4cf6c00-9090-11e9-8553-1328d9bca6a9.png)
без `raise` всё красиво

2019-06-16 16:52 UTC, kiselyovanat commented on invoke_layer.py
> +        return
сделано

2019-06-16 16:54 UTC, kiselyovanat commented on CCPTool/invoke_layer.py
> +import subprocess
сделано

2019-06-16 16:55 UTC, kiselyovanat commented on CCPTool/invoke_layer.py
> +    command = ['./main', filename]
сделано

2019-06-16 16:55 UTC, kiselyovanat commented on CCPTool/invoke_layer.py
> +    return(output,errors)
сделано

2019-06-16 16:58 UTC, kiselyovanat commented on CCPTool/invoke_layer.py
> +    return(output,errors)
нужен ли вообще теперь здесь `return`?

2019-06-17 08:04 UTC, vveiln commented on invoke_exceptions.py
> +class InvokeExcepction(Exception):
Опечатка. `InvokeException`

2019-06-17 08:04 UTC, vveiln commented on invoke_layer.py
> +        NoMainException(exc)
Ладно, давай все-таки сделаем без принта и с эксепшеном:
``` python
except Exception as exc:
    raise NoMainException(exc)
```

2019-06-17 08:04 UTC, vveiln commented on invoke_layer.py
> +        NoMainException(exc)
А вообще делать просто `NoMainException(exc)` не имело смысла, т.е. если удалять `raise`, то и само исключение тоже

2019-06-17 08:04 UTC, vveiln commented on invoke_layer.py
> +            print ("!!! VIRUS !!!")
Давай здесь сделаем
``` python
return ...
```
вместо
``` python
print (...)
return
```
(точки заменить на то, что принтилось)

и тогда везде, где вызывается эта функция, нужно возвращаемый результат тоже возвращать, т.е.

` return parse(...)` 
(тут точки - это аргумент, с которым была вызвана функция. мне просто не хочется его название смотреть)

2019-06-17 08:15 UTC, maurges commented on CCPTool/main.cpp
> +			cout << " signature at function " << *iter << endl
Забыла `;`
=3

2019-06-17 08:15 UTC, maurges commented on invoke_layer.py
> +        NoMainException(exc)
Красиво, конечно, только это неправильное поведение. Мы же кидаем исключения чтобы их ловить, а здесь ты ничего не кидаешь, просто кладёшь программу, если возникает ошибка.
Я почитал stackoverflow, и такой длинный трейсбек, который ты видела на предыдущем скриншоте - это нормально для питона.

2019-06-18 03:14 UTC, kiselyovanat commented on CCPTool/main.cpp
> +			cout << " signature at function " << *iter << endl
сделано

2019-06-18 03:14 UTC, kiselyovanat commented on invoke_layer.py
> +            print ("!!! VIRUS !!!")
сделано

2019-06-18 03:15 UTC, kiselyovanat commented on invoke_exceptions.py
> +class InvokeExcepction(Exception):
сделано

2019-06-18 03:15 UTC, kiselyovanat commented on invoke_layer.py
> +        NoMainException(exc)
сделано

2019-06-18 05:05 UTC, maurges requested changes

2019-06-18 05:05 UTC, maurges commented on invoke_layer.py
> +    return ("NOT VIRUS")
У `return` не нужны скобки, это же не функция. Здесь и строкой выше.

2019-06-18 05:05 UTC, d86leader commented on invoke_layer.py
> +    return ("NOT VIRUS")
Ещё одно. Это же библиотечная функция. Представь, что ты пишешь супервраппер и вызываешь вот функцию `invoke`. По этим возвращаемым значениям неудобно проверять, нашёлся вирус или нет. Писать `if invoke("suspicious", 0x1337) == "!!! VIRUS !!!"` - ну камон.
Можно сделать, чтобы оно возвращало булево значение (и тогда в комментариях указать, что это значение означает), либо можно возвращать отсюда enum типа
```
class CCPToolResult(Enum):
 virus = 1
 safe  = 2
```
Про енумы в питоне можно вот здесь почитать: https://www.python.org/dev/peps/pep-0435/

2019-06-18 16:24 UTC, kiselyovanat commented on invoke_layer.py
> +    return ("NOT VIRUS")
Думаю, идея с булевыми значениями мне понятнее)

2019-06-18 17:08 UTC, d86leader commented on invoke_layer.py
> +    return ("NOT VIRUS")
Окей, теперь добавь поясняющие комментарии. Всё же когда функция `invoke()` возвращает `False`, непонятно, что это значит.

2019-06-18 17:08 UTC, d86leader commented on invoke_layer.py
> +    return ("NOT VIRUS")
А соре я слепой.

2019-06-18 17:09 UTC, maurges approved these changes

2019-06-19 02:06 UTC, vveiln approved these changes

2019-06-19 02:06 UTC, merged