Create functionsname.py
lyawaf/antivirus pull request #20
Opened 2019-06-16 07:25 UTC by lizatrif

[+] program for obtaining function names and their physical addresses

2019-06-16 12:29 UTC, maurges requested changes

2019-06-16 12:29 UTC, maurges commented on functionsname.py
> +#! /usr/bin/env python
Мы python3 используем же.

2019-06-16 12:29 UTC, maurges commented on functionsname.py
> +    def show(self):
Стоит вместо этого делать сделать `def __str__(self):`, чтобы потом можно было использовать `print(name_address)` и `str(name_address)`

2019-06-16 12:29 UTC, d86leader commented on functionsname.py
> +    p = Popen(['objdump', '-x', 'nlbig'], stdin=PIPE, stdout=PIPE, stderr=PIPE)
Сюда, наверное, надо название файла, который парсим, из аргумента функции передавать? Мы же не будем каждый раз `nlbig` парсить. (;

2019-06-16 12:29 UTC, d86leader commented on functionsname.py
> +    output, err = p.communicate(b"input data that is passed to subprocess' stdin")
Процессу передаёшь какие-то лишние данные.

2019-06-16 12:29 UTC, d86leader commented on functionsname.py
> +    #print n
Why not use: `n = len(lines)` ?

2019-06-16 12:29 UTC, d86leader commented on functionsname.py
> +    a = "Sections:"
Понятные названия переменных. <:

2019-06-16 12:29 UTC, d86leader commented on functionsname.py
> +            symb = i # symb - номер секции SYMBOL TABLE:
`break` забыла? Стоит вообще вместо этих двух циклов использовать `lines.index("SYMBOL TABLE:")`

2019-06-16 12:29 UTC, d86leader commented on functionsname.py
> +        adress.append(words[b])
Предыдущие десять строк - какая-то магия. ) Тут, видимо, просто берутся слова с определённых мест? Во-первых, почему бы не убрать `reverse()` и не использовать `pop(0)`, а во-вторых, зачем вообще нужен `pop()`, если можно просто взять `a = words[1]`. И в любом случае, не хватает комментариев, поясняющих, что же здесь происходит.
Ну и опять названия переменных `a`, `b`. )

2019-06-16 12:29 UTC, d86leader commented on functionsname.py
> +    c = "*ABS*"
Вот здесь тоже поясни, зачем это нужно. И почему мы, например, не пропускаем `"*UND*"`?

2019-06-16 12:29 UTC, d86leader commented on functionsname.py
> +start()
Сделай ещё `if __name__ == "__main__":`

2019-06-16 12:29 UTC, d86leader commented on functionsname.py
> +            continue
А вообще там могут быть символы не только из `ABS`, `.text` или `UND`, могут ещё быть символы из `.data` и, наверное, из других секций, и их тоже надо пропускать (в parsing-exe, например, они есть). То есть вместо этого всего нужно просто оставить проверку на то, что это точно из секции `.text`.

2019-06-16 12:29 UTC, d86leader commented on functionsname.py
> +    f_adress = []
А почему бы не сделать список типа `[("coolfunction", 228), ("nicemethod", 1337)]`? Ведь вряд ли где-то нужно знать имя функции, но не знать её адрес.

2019-06-16 12:29 UTC, d86leader commented on functionsname.py
> +        f_adress.append(a)
Опять немножко магическое место с `reverse()`-ами и `pop()`-ами.
Но вот ещё что: здесь ты, я так понял, работаешь с символами в том числе из секции `.data`. Они нам на самом деле не нужны, то есть можно просто один раз посчитать адрес начала секции `.text`, и не делать поиск по `adress`.

2019-06-16 12:29 UTC, d86leader commented on functionsname.py
> +class Funtcions(object):
Хотел сказать, что тут опечатка в названии класса, но он к тому же ещё и нигде не используется.

2019-06-16 12:29 UTC, d86leader commented on functionsname.py
> +class NameAdress(object):
Хотел сказать, что тут опечатка в названии класса, но он к тому же ещё и нигде не используется.

2019-06-16 12:32 UTC, lizatrif commented on functionsname.py
> +#! /usr/bin/env python
исправлю

2019-06-16 12:32 UTC, lizatrif commented on functionsname.py
> +    p = Popen(['objdump', '-x', 'nlbig'], stdin=PIPE, stdout=PIPE, stderr=PIPE)
исправлю, будет передаваться аргументом

2019-06-16 12:33 UTC, lizatrif commented on functionsname.py
> +            continue
нам нужны только данные из секции .text?
я по твоему большому файлу убирала только ABS и UND, а все остальные секции использовала

2019-06-16 12:34 UTC, lizatrif commented on functionsname.py
> +    f_adress = []
не совсем поняла тебя)

2019-06-16 12:35 UTC, lizatrif commented on functionsname.py
> +        f_adress.append(a)
магия в pop() и reverse() для получения первого и последнего элементов списка

2019-06-16 12:55 UTC, lizatrif commented on functionsname.py
> +    def show(self):
убрала вообще)

2019-06-16 12:59 UTC, lizatrif commented on functionsname.py
> +    output, err = p.communicate(b"input data that is passed to subprocess' stdin")
stdin убрала, остальное нельзя

2019-06-16 12:59 UTC, lizatrif commented on functionsname.py
> +    #print n
хз) исправила)

2019-06-16 13:01 UTC, lizatrif commented on functionsname.py
> +    a = "Sections:"
убрала

2019-06-16 13:03 UTC, lizatrif commented on functionsname.py
> +            symb = i # symb - номер секции SYMBOL TABLE:
исправила

2019-06-16 13:12 UTC, lizatrif commented on functionsname.py
> +        adress.append(words[b])
исправила

2019-06-16 13:21 UTC, lizatrif commented on functionsname.py
> +    c = "*ABS*"
*ABS* когда первый раз встречается - после этого начинаются функции - до снова описывались секции

2019-06-16 13:21 UTC, lizatrif commented on functionsname.py
> +start()
ок

2019-06-16 14:56 UTC, d86leader commented on functionsname.py
> +#! /usr/bin/env python
Исправила совсем убрав эту строку? Мы же вроде договорились их делать. (-:
@vveiln

2019-06-16 15:05 UTC, lizatrif commented on functionsname.py
> +#! /usr/bin/env python
ну так если третий питон?)

2019-06-16 15:25 UTC, maurges requested changes

2019-06-16 15:25 UTC, d86leader commented on functionsname.py
> +            functions.append(trash.pop())
Вместо `pop()` можно использовать просто `trash[-1]`. А ещё бы этой переменной тоже более нормальное название сделать. >__>

2019-06-16 15:25 UTC, d86leader commented on functionsname.py
> +            functions.append(trash.pop())
А вообще тут опять странная логика. Ты же здесь вообще работаешь только с последним элементом из этого `trash`. Тогда зачем тебе весь массив целиком, если можно просто запоминать последний элемент? Ну там делать не `trash.append(word)`, а просто `trash = word`

2019-06-16 15:25 UTC, d86leader commented on functionsname.py
> +            functions.append(trash.pop())
То есть нормальное название переменной - это не придирка, оно позволило бы мне (и может тебе)) понять, зачем эта переменная тут нужна.

2019-06-16 15:25 UTC, d86leader commented on functionsname.py
> +                    word = re.sub(r"\d+", "", word, flags=re.UNICODE)
Вот эта строчка бесполезна. Она записывает re.sub во временную переменную цикла. Можешь проверить своими руками:
```
a = ["1", "2", "3"]
for word in a:
    word = "x"
print(a) # -> ["1", "2", "3"]
```

2019-06-16 15:25 UTC, d86leader commented on functionsname.py
> +    filename="nlbig"
(=
Следующий шаг - сделать возможность передавать имя файла из командной строки:
```
    if len(sys.argv) < 2:
        print("Usage: {} file".format(sys.argv[0]))
        sys.exit(1)
```
Ну и где-то наверху добавить `import sys`

2019-06-16 15:25 UTC, d86leader commented on functionsname.py
> +    output, err = p.communicate(b"input data that is passed to subprocess' stdin")
В принципе вот эту строку `b"input data ..."` можно убрать вроде, нет?

2019-06-16 15:25 UTC, d86leader commented on functionsname.py
> +import subprocess
Лишний импорт.

2019-06-16 15:26 UTC, d86leader commented on functionsname.py
> +#! /usr/bin/env python
Ну так если третий питон, то нужно просто написать `#!/usr/bin/env python3` (=

2019-06-16 16:19 UTC, lizatrif commented on functionsname.py
> +    filename="nlbig"
можешь пояснить, не могу понять куда это написать(

2019-06-16 17:36 UTC, maurges requested changes

2019-06-16 17:36 UTC, d86leader commented on functionsname.py
> +        i = i + 1
1) Здесь мы ищем последнее вхождение ABS, окей. Я сейчас глянул один бинарь, и в нём ещё до последнего вхождения были какие-то написанные мною функции.
2) Если в бинаре вообще нет ни одного вхождения ABS, то тут будет ошибка с неопределённой переменной.

Так может вообще это опустить? Просто брать и смотреть все символы с самого начала.

2019-06-16 17:36 UTC, d86leader commented on functionsname.py
> +            adress=words[index[3]]
1) Опечатка в названии переменной. )
2) А что если мы не нашли секцию .text в файле?

2019-06-16 17:36 UTC, d86leader commented on functionsname.py
> +    if len(sys.argv) < 2:
Добавь `import sys` наверх файла ещё. И не забывай тестировать, работает ли твоя программа. :>

2019-06-16 17:36 UTC, d86leader commented on functionsname.py
> +        i = i + 1
Если смотреть вообще все символы, то нужно будет пропустить в начале symbol table-a несколько строчек, в которых записано типа `d  .hash  0000000000000000      .hash`

2019-06-17 03:18 UTC, lizatrif commented on functionsname.py
> +        i = i + 1
ок, смотрю весь код от начала секции SYMBOL TABLE, про .hash можешь скрин скинуть посмотреть пожалуйста)

2019-06-17 03:20 UTC, lizatrif commented on functionsname.py
> +            adress=words[index[3]]
1. исправила
2. пустой массив будет

2019-06-17 03:21 UTC, lizatrif commented on functionsname.py
> +    if len(sys.argv) < 2:
исправила

2019-06-17 08:14 UTC, d86leader commented on functionsname.py
> +            adress=words[index[3]]
Насчёт 2: ага, и будет непонятная (для пользователя) ошибка, когда ты попытаешься из этого массива что-то взять. Думаю, было бы здорово сделать как у Наташи: классы исключений, чтобы кидать, когда:
1) Нет секции `.text`
2) Нет таблицы символов
3) `objdump` не запустился
Можно использовать https://github.com/vveiln/python-internship/blob/develop/src/transport_exception.py в качестве примера.

2019-06-17 08:47 UTC, vveiln requested changes

2019-06-17 08:47 UTC, vveiln commented on functionsname.py
> +    sect=lines.index("Sections:")
Не хватает пробелов между `=`, `,`, `==`, `+`

2019-06-17 08:47 UTC, vveiln commented on functionsname.py
> +    n = len(lines)
почему переменная называется `n` и где она используется?
А, я нашла, где. Насколько я вижу, она используется один раз, поэтому нет особого смысла ее выделять. Если я что-то пропустила и она используется много раз, то назови ее как-нибудь поосмысленней и определяй ближе к месту первого использования

2019-06-17 08:47 UTC, vveiln commented on functionsname.py
> +    sect=lines.index("Sections:")
Ну между `-` тоже. Ну всем таким, короче

2019-06-17 08:47 UTC, vveiln commented on functionsname.py
> +    symb=lines.index("SYMBOL TABLE:")
Зачем сокращать названия? Вроде они размер кода не критично увеличат, а вот читабельность резко падает

2019-06-17 08:47 UTC, vveiln commented on functionsname.py
> +    name = ".text"
Тоже название ни о чем не говорит особо. Мб как-нибудь типа text_section_literal, но это первое, что в голову пришло

2019-06-17 08:47 UTC, vveiln commented on functionsname.py
> +            if word.strip():
Если строки ты разбиваешь по `\n`, слова - по пробелу, то что ты проверяешь стрипом? табы? или что-то еще?

2019-06-17 08:47 UTC, vveiln commented on functionsname.py
> +            address=words[index[3]]
Адрес чего?

2019-06-17 08:47 UTC, vveiln commented on functionsname.py
> +                lastworld = word
snake case используем для названия переменных
`last_word`

2019-06-17 08:50 UTC, vveiln commented on functionsname.py
> +    f_adress = []
В текущем варианте это будет выглядеть как
``` python
functions = ["coolfunction", "nicemethod"]
f_address = [228, 1337]
```

Никита предлагает сделать один список, содержащий тьюплы (имя функции, адрес функции), как я понимаю

2019-06-17 15:28 UTC, lizatrif commented on functionsname.py
> +    sect=lines.index("Sections:")
исправила

2019-06-17 15:29 UTC, lizatrif commented on functionsname.py
> +    n = len(lines)
убрала переменную

2019-06-17 15:35 UTC, lizatrif commented on functionsname.py
> +    symb=lines.index("SYMBOL TABLE:")
исправила

2019-06-17 15:35 UTC, lizatrif commented on functionsname.py
> +    name = ".text"
исправила

2019-06-17 15:37 UTC, lizatrif commented on functionsname.py
> +            if word.strip():
на самом деле пустоты между столбцами разбивались на отдельные слова с пробелами, так вот этим стрипом я беру слова, в которых что-то помимо пробелом находится

2019-06-17 15:37 UTC, lizatrif commented on functionsname.py
> +            if word.strip():
на самом деле пустоты между столбцами разбивались на отдельные слова с пробелами, так вот этим стрипом я беру слова, в которых что-то помимо пробелом находится

2019-06-17 15:38 UTC, lizatrif commented on functionsname.py
> +            if word.strip():
на самом деле пустоты между столбцами разбивались на отдельные слова с пробелами, так вот этим стрипом я беру слова, в которых что-то помимо пробелом находится

2019-06-17 15:39 UTC, lizatrif commented on functionsname.py
> +            address=words[index[3]]
дописала понятнее

2019-06-17 15:40 UTC, lizatrif commented on functionsname.py
> +                lastworld = word
исправила

2019-06-17 16:01 UTC, maurges requested changes

2019-06-17 16:01 UTC, maurges commented on functionsname.py
> +            if word.strip():
Для этого можно использовать `lines[i].split()` - без аргументов.

2019-06-17 16:01 UTC, maurges commented on functionsname.py
> +                last_world = word
Цикл излишний. Можно просто `last_word = words[-1]`
Кстати, опечатка в названии переменной.
Кстати, более говорящее название тут бы тоже не помешало.

2019-06-17 16:01 UTC, maurges commented on functionsname.py
> +    print (functions_address, functions_names)
Нужно `return` а не принт, это же библиотечная функция. А принт можно сделать в мейне внизу, где ты вызываешь эту функцию.

2019-06-17 16:01 UTC, d86leader commented on functionsname.py
> +    functions_address = []
Посмотри, пожалуйста, новое разъяснение Юли в старом треде по этому поводу.

2019-06-17 16:08 UTC, lizatrif commented on functionsname.py
> +                last_world = word
первое исправила, во втором вообще избавилась от переменной

2019-06-17 16:10 UTC, lizatrif commented on functionsname.py
> +    print (functions_address, functions_names)
ok

2019-06-17 16:20 UTC, lizatrif commented on functionsname.py
> +    f_adress = []
Имеется в виду двумерный список, верно?

2019-06-17 16:33 UTC, lizatrif commented on functionsname.py
> +    f_adress = []
сделала

2019-06-17 16:33 UTC, lizatrif commented on functionsname.py
> +            if word.strip():
использовала

2019-06-17 16:35 UTC, lizatrif commented on functionsname.py
> +    functions_address = []
ok

2019-06-17 17:32 UTC, maurges requested changes

2019-06-17 17:32 UTC, d86leader commented on functionsname.py
> +        ObjdumpFailure('Objdump is failure')
`raise` исключению сделать нужно.
`return` избыточен, код после `raise` и так не будет выполняться.

2019-06-17 17:32 UTC, d86leader commented on functionsname.py
> +        NoSymbolsSectionError('No SYMBOL TABLE section')
То же что и выше про raise и return

2019-06-17 17:32 UTC, d86leader commented on functionsname.py
> +        return
Ну и здесь return не нужен.

2019-06-17 17:32 UTC, d86leader commented on functionsname.py
> +    return (functions)
скобки не нужны, это же не функция

2019-06-17 17:35 UTC, lizatrif commented on functionsname.py
> +            adress=words[index[3]]
сделано

2019-06-17 17:51 UTC, d86leader commented on functionsname.py
> +    for i in range(section_index + 2, symbols_index, 2):
Итерироваться по индексу - это та-ак не pythonic и так не 2к19-й.
Лучше использовать `for line in lines[section_index + 2 : symbols_index : 2]`

2019-06-17 17:51 UTC, d86leader commented on functionsname.py
> +    for i in range(symbols_index + 1, len(lines) - 3):
Здесь тоже лучше итерироваться по элементам, а не индексам:
`for line in lines[symbols_index + 1 : -3]`

2019-06-18 16:51 UTC, lizatrif commented on functionsname.py
> +    for i in range(section_index + 2, symbols_index, 2):
ok

2019-06-18 16:53 UTC, lizatrif commented on functionsname.py
> +    for i in range(symbols_index + 1, len(lines) - 3):
ок

2019-06-18 17:18 UTC, maurges requested changes

2019-06-18 17:18 UTC, d86leader commented on functionsname.py
> +        output, err = p.communicate()
Давай ещё как у Наташи кидать `ObjdumpFailure` когда `err != ""`

2019-06-18 17:18 UTC, d86leader commented on functionsname.py
> +    section_index = lines.index("Sections:")
Наверное это почти всегда митигируется предложением выше, но вот что: если запустить скрипт на файле, в котором нет `Sections:`, то получишь неожиданный `ValueError`.

Так что лучше эту вещь поместить в `try` чуть пониже, и исключение, которое там кидается, переименовать во что-то более общее, что бы оно показывало, что какую-то таблицу (секций или символов) мы в файле не нашли.

2019-06-19 04:31 UTC, maurges requested changes

2019-06-19 04:31 UTC, d86leader commented on functionsname.py
>      output, err = process.communicate()
На всякий случай верни это обратно в `try` блок.

2019-06-19 04:47 UTC, maurges requested changes

2019-06-19 04:47 UTC, d86leader commented on functionsname.py
> +        raise NoSectionError('No Section: section')
Ошибки с таким названием не существует. Забыла переименовать?

2019-06-19 04:47 UTC, d86leader commented on functionsname.py
> +        raise NoSectionError('No SYMBOL TABLE section')
Здесь, видимо, тоже.

2019-06-19 04:47 UTC, d86leader commented on functionsname.py
> +        raise NoSectionError('No .text section')
И-и здесь тоже.

2019-06-19 04:48 UTC, lizatrif commented on functionsname.py
> +        raise NoSectionError('No Section: section')
и подумала, что можно объединить. Ведь мы не находим секцию, а какую конкретно указано в тексте. Разве так нельзя?

2019-06-19 05:32 UTC, maurges approved these changes

2019-06-19 06:01 UTC, vveiln requested changes

2019-06-19 06:01 UTC, vveiln commented on functionsname.py
> +import re
Эта библиотека где-то используется?

2019-06-19 06:01 UTC, vveiln commented on functionsname.py
> +import traceback
А эта?

2019-06-19 06:01 UTC, vveiln commented on functionsname.py
> +    else:
что-то не так с отступами, кажется

2019-06-19 06:01 UTC, vveiln commented on functionsname.py
> +def start(filename):
Кстати, а что с названием функции? Оно не очень понятное

2019-06-19 06:01 UTC, vveiln commented on functionsname.py
> +def start(filename):
Что мы делаем в этой функции? Вроде как находим функции в файле и их адреса, так?
Тогда мы что-то подобное и должны отразить в названии, например, `get_functions_addresses`

2019-06-19 06:01 UTC, vveiln commented on functionsname.py
> +    print (functions)
мы же обычно не пишем пробел между именем функции и скобками, так и тут тоже не надо

2019-06-19 06:01 UTC, vveiln commented on functionsname.py
> +        raise ObjdumpFailure('Objdump is failure')
У нас класс исключений называется `ObjdumpFailure`, какую информацию нам добавляет сообщение, которое ты передаешь? Да и само сообщение некорректное. Мы вообще, получается, полностью гасим информацию, пойманную в блоке, поэтому, чтобы сильно не запариваться, давай вместо того сообщения будем передавать то, что содержит эксепшн

2019-06-19 06:01 UTC, vveiln commented on functionsname.py
> +        raise NoSectionError('No Section: section')
Здесь мы, получается, пытаемся найти строку, содержащую `"Sections:"`, и, честно говоря, сообщение ошибки скорее путает, чем проясняет что-то. Я бы его просто сформулировала более понятным образом, чтобы было понятно, что в дампе файла нет секций.

2019-06-19 06:01 UTC, vveiln commented on functionsname.py
> +        symbols_index = lines.index("SYMBOL TABLE:")
Давай весь файл будет содержать одинаковый тип скобок? Если одинарные, то одинарные везде, а если двойные, то везде двойные

2019-06-19 06:02 UTC, d86leader commented on functionsname.py
> +    else:
Нет, это else для for-a.

2019-06-19 06:04 UTC, vveiln commented on functionsname.py
> +    else:
Мой косяк, забудь об этом коментарии

2019-06-20 00:41 UTC, vveiln approved these changes

2019-06-20 00:41 UTC, merged